spring.application.name=JRTP701-MiniProj01-CURDOperations


server.port=4041

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=nitraja
spring.datasource.password=nitraja

#orm/jpa properties(optional for H2DB)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect