
spring:
    application:
        name: JRTP701-MiniProj01-CURDOperations
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: nitraja
        password: nitraja
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
server:
    port: 4041

plan:
  module:
      messages:
          save-success: Travel plan is saved with id value
          save-failure: Travel plan is not saved
          find-by-id-failure: Travel plan is not found
          update-success: Travel plan is updated
          update-failure: Travel plan is not found for updation
          delete-success: Travel plan is deleted
          delete-failure: Travel pla is not found for deletion
          status-change-success: Travel plan status is changed
          status-change-failure: Travel plan is not found for status change